# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Services
  description: A list of services
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  description_text: ""
  component_theme: ""
  services:
    - title: ""
      description_html: ""
      image: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: Services
  description_text: "Our specialised team has the skill and experience to provide
    a range of services. The utmost care is taken with all our work. The main
    streams of work we perform are as follows:"
  component_theme: Light
  services:
    - title: Property
      description_html: <p>The first contact with law for many people is when buying a
        first home. We can assist you through this process, managing the details
        and offering advice. When or if the time comes, we'll also assist with
        selling your home.</p><p>We have expertise in the consent process for
        new developments and improvements, as well as helping you manage assets
        through trusts.</p>
      image: https://unsplash.it/960/350?image=946
    - title: Employment
      description_html: <p>If you're looking to employ or be employed, we offer solid
        advice and assistance with creating and reading agreements. We have a
        proven track record handling disputes.</p>
      image: https://unsplash.it/960/350?image=668
    - title: Business
      description_html: <p>From structuring and mergers to shareholder agreements, we
        are here to assist you when starting, buying, running or selling your
        business.</p>
      image: https://unsplash.it/960/350?image=376

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
