[component]
structures = ["content_blocks"]
label = "Contact Form"
description = "Generic contact form"
icon = "wysiwyg"
tags = ["Text"]

[props]
heading = "Contact"
lower_text = "Come see us in person, give us a call, or send us a message with your details and we'll be in contact shortly after. No obligations and your first meeting is free. "
form_submission_email = "admin@example.com"                                                                                                                                         # The email address form submissions will be sent to
component_theme = "Light"

[props.company_details]
address = "1 Bond Street, Dunedin, New Zealand"
postal_address = ""
phone = ""
email = "support@example.com"
