[component]
structures = ["content_blocks"]
label = "Image And Text Blocks"
description = "A group of side by side text and image blocks"
icon = "wysiwyg"
tags = ["Content"]

[[props.blocks]]
heading_html = "<h2>How can we <strong>double</strong> our sales revenue?</h2>"
content_html = "<p>Hydra learns your business. By analyzing your sales data, Hydra optimizes your sales process and show you where you should be spending your resources. </p>"
image = "/images/dashboard.png"
content_arrangement.select = ["Left", "Right"]
component_theme = "Light"

[props.blocks.button]
button_label = "Get Started Free"
button_link_url = "/sign-up/"
button_variant.select = ["Transparent", "Filled"]
