[component]
structures = ["content_blocks"]
label = "Posts List"
description = "Lists all of the site's blog posts"
icon = "wysiwyg"
tags = ["Collections"]

[props]
show_posts = true
heading = "Blog"
content_text = "Get an introduction to some industry topics and stay informed with our in-depth articles."
component_theme = "Light"
