[component]
structures = ["content_blocks"]
label = "Button"
description = "Generic customisable button"
icon = "wysiwyg"
tags = ["Generic"]

[props]
label = "Get Started Free"
link_url = "/sign-up/"
variant.select = ["Transparent", "Filled", "Plain Text"]
open_in_new_tab = false
