# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Button
  description: Generic customisable button
  icon: wysiwyg
  tags:
    - Generic

# Defines the structure of this component, as well as the default values
blueprint:
  label: ""
  link_url: ""
  variant: Transparent
  open_in_new_tab: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  label: Get Started Free
  link_url: /sign-up/

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  variant:
    type: select
    options:
      values:
        - Transparent
        - Filled
        - Plain Text
