light_theme_settings:
  page_color: "#ffffff"
  component_alt_color: "#ffffff"
  brand_color: "#3e3f46"
  headings_color: "#000000"
  text_color: "#888"
  light_text_color: "#ffffff"
  link_color: "#4489b1"
  button_fill_color: "#4489b1"
  button_fill_text_color: "#ffffff"
  tag_color: '#eeeeee'
  navigation_color: '#FEFEFE'
  footer_color: '#fefefe'
  footer_link_color: '#3A4145'
  footer_link_hover_color: '#73a9c9'
dark_theme_settings:
  page_color: "#131313"
  component_alt_color: "#1a1a1a"
  brand_color: "#202020"
  headings_color: "#ffffff"
  text_color: "#c4c4c4"
  light_text_color: "#ffffff"
  link_color: "#00a4ca"
  button_fill_color: "#737373"
  button_fill_text_color: "#ffffff"
  tag_color: '#444444'
  navigation_color: '#FEFEFE'
  footer_color: '#fefefe'
  footer_link_color: '#3A4145'
  footer_link_hover_color: '#73a9c9'
body_font: 'Open Sans'
content_font_size_number: 2.1