source "https://rubygems.org"


group :jekyll_plugins do
  # Use this for local development, and comment out the github reference
  # gem 'cc-template-components', :path => '../../cc-template-components'

  # Use this for production and comment out local reference
  gem 'cc-template-components', git: "https://github.com/cloudcannon/cc-template-components.git", :branch => 'main' 

  gem "jekyll-bookshop", ">= 2.0.0.pre.beta"
  gem "cloudcannon-jekyll-bookshop", ">= 2.0.0.pre.beta"
  gem 'jekyll-watch', :git => "https://github.com/CloudCannon/jekyll-watch"
  gem 'jekyll-postcss-v2'
  gem 'jekyll-archives', '~> 2.2.1'
  gem 'jekyll-feed', '~> 0.15.1'
end
