[component]
structures = ["content_blocks"]
label = "Frequently asked questions"
description = "Questions and answers section"
icon = "wysiwyg"
tags = ["Content"]

[props]
heading = "Pricing FAQ"
component_theme = "Light"

[[props.questions]]
question_text = "What types of payment do you accept?"
answer_text = "Credit cards including MasterCard, Visa or American Express."
[[props.questions]]
question_text = "Do you offer pricing for nonprofit organizations?"
answer_text = "Yes, send us a message and we'll set you up on our nonprofit pricing."
[[props.questions]]
question_text = "Can I change my plan at a later time?"
answer_text = "Yes, you can upgrade and downgrade your plan at anytime."
