# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Frequently asked questions
  description: Questions and answers section
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  component_theme: ""
  questions:
    - question_text: ""
      answer_text: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: Pricing FAQ
  component_theme: Light
  questions:
    - question_text: What types of payment do you accept?
      answer_text: Credit cards including MasterCard, Visa or American Express.
    - question_text: Do you offer pricing for nonprofit organizations?
      answer_text: Yes, send us a message and we'll set you up on our nonprofit pricing.
    - question_text: Can I change my plan at a later time?
      answer_text: Yes, you can upgrade and downgrade your plan at anytime.

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
