[component]
structures = ["content_blocks"]
label = "Updates"
description = "A grid of items detailing recent updates"
icon = "wysiwyg"
tags = ["Content"]

[props]
heading = "Updates"
component_theme = "Light"

[[props.updates]]
image = "https://unsplash.it/570/400?image=1018"
date = 2021-08-05
title = "$5000 and counting"
content_text = "Wow what a response from the sheep community. Black sheep, white sheep, fluffy sheep, we’re all in this together. I believe we can inspire all animals to stand up for what’s right and receive recognition for the hard work we do every day."

[[props.updates]]
image = "https://unsplash.it/570/400?image=1080"
date = 2021-08-02
title = "We've raised $2000!"
content_text = "Thank you do everyone who has made contributions. This money is going towards reaching sheep in paddocks far and wide. The revolution has begun."

[[props.updates]]
image = "https://unsplash.it/570/400?image=1044"
date = 2021-08-01
title = "Our first $1000"
content_text = "This is just the beginning. We’re working harder than ever for the rights of sheep everywhere."
