# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Reviews
  description: Text with a grid of reviews
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  content_html: ""
  component_theme: ""
  reviews:
    - name: ""
      review_text: ""
      image: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: ""
  content_html: <p>This is the Justice template from <a
    href='https://cloudcannon.com/'>CloudCannon</a>. Justice is strong
    foundation for the web presence of a law firm or business. It's filled with
    fictitious example content to get you started.</p><p>Justice Law is
    professional representation. Practicing for over 50 years, our team have the
    knowledge and skills to get you results.</p>
  component_theme: Light
  reviews:
    - name: Joice Carmold
      review_text: We use Justice Law in all our endeavours. They offer an
        unparalleled service when it comes to running a business.
      image: https://placekitten.com/g/60/60?a=.png
    - name: Peter Rottenburg
      review_text: Justice Law are the best of the best. Being local, they care about
        people and have strong ties to the community.
      image: https://www.fillmurray.com/60/60?a=.png
    - name: D. and G. Gibbleston
      review_text: Justice Law were everything we could have hoped for when buying our
        first home. Highly recommended to all.
      image: https://placebear.com/60/60?a=.png

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
