[component]
structures = ["content_blocks"]
label = "Reviews"
description = "Text with a grid of reviews"
icon = "wysiwyg"
tags = ["Content"]

[props]
heading = ''
content_html = "<p>This is the Justice template from <a href='https://cloudcannon.com/'>CloudCannon</a>. Justice is strong foundation for the web presence of a law firm or business. It's filled with fictitious example content to get you started.</p><p>Justice Law is professional representation. Practicing for over 50 years, our team have the knowledge and skills to get you results.</p>"
component_theme = "Light"

[[props.reviews]]
name = "Joice Carmold"
review_text = "We use Justice Law in all our endeavours. They offer an unparalleled service when it comes to running a business."
image = "https://placekitten.com/g/60/60?a=.png"

[[props.reviews]]
name = "Peter Rottenburg"
review_text = "Justice Law are the best of the best. Being local, they care about people and have strong ties to the community."
image = "https://www.fillmurray.com/60/60?a=.png"

[[props.reviews]]
name = "D. and G. Gibbleston"
review_text = "Justice Law were everything we could have hoped for when buying our first home. Highly recommended to all."
image = "https://placebear.com/60/60?a=.png"
