[component]
structures = ["content_blocks"]
label = "Map"
description = "Google maps page block"
icon = "wysiwyg"
tags = ["Content"]

[props]
google_maps_api_key = ''
component_theme = "Light"

[props.map]
latitude = -45.8779128
longitude = 170.5026709
address = "1 Bond Street, Dunedin, New Zealand"
zoom = 13
