# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Map
  description: Google maps page block
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  google_maps_api_key: ""
  component_theme: ""
  map:
    latitude: -45.8779128
    longitude: 170.5026709
    address: ""
    zoom: 13

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  google_maps_api_key: ""
  component_theme: Light
  map:
    address: 1 Bond Street, Dunedin, New Zealand

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
