[component]
structures = ["content_blocks"]
label = "Gallery"
description = "An image/link gallery"
icon = "wysiwyg"
tags = ["Gallery"]

[[props.details]]
show_details = true
heading = "Some of our work"
subheading = "We take pride in our previous work and our happy customers. We cater to any sector to boost business and increase exposure."
text_color = "#ffffff"
button_label = "View Full Portfolio →"
button_link_url = "/portfolio/"
button_variant.select = ["Transparent", "Filled"]

[props]
content_arrangement.select = ["Left", "Right"]
image_borders = true
component_theme = "Dark"

[[props.gallery_items]]
image = "//placekitten.com/440/440?a=.png"
image_title = "Item One"
image_caption = "Caption Text"
link_url = "//placekitten.com/440/440?a=.png"
