[component]
structures = ["content_blocks"]
label = "Pricing Plans"
description = "Pricing plan cards"
icon = "wysiwyg"
tags = ["Marketing"]

[props]
heading = 'Find the perfect plan for your business'
subheading = 'All plans include our award winning sales optimization solution to track your sales in real time.'
component_theme = "Light"

[[props.plans]]
title = "Basic"
card_color = "#8e8e8e"
price = "$25 per month"
button_url = "#"

[[props.plans.features]]
feature = "Up to 5 users"

[[props.plans.features]]
feature = "Basic lead scoring"

[[props.plans.features]]
feature = "CRM"

[[props.plans.features]]
feature = "Basic reporting"

[[props.plans.features]]
feature = "Sales map"
