[component]
structures = ["content_blocks"]
label = "Header With Image"
description = "Page header with headings, a button and an image"
icon = "wysiwyg"
tags = ["Headers"]

[props]
heading_html = "<h1>The last sales CRM <strong>you'll ever need</strong></h1>"
subheading_html = "<p>Track and optimize your sales team in real time.</p>"
text_color = "#ffffff"
content_alignment = "Center"
button_label = "Get Started Free"
button_link_url = "/sign-up/"
button_variant.select = ["Transparent", "Filled"]
image = "/images/dashboard.png"
component_theme = "Light"
