[component]
structures = ["content_blocks"]
label = "Call to action mailing list"
description = "Call to action block with a subscribe to mailing list option"
icon = "wysiwyg"
tags = ["Content"]

[props]
heading = "Join us"
lower_text = "Sign up to hear the latest news and progress in our fight for the sheep vote."
form_submission_email = ""
submit_success_url = "/contact-success/"
component_theme = "Light"
