# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Call to action mailing list
  description: Call to action block with a subscribe to mailing list option
  icon: wysiwyg
  tags:
    - Content

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  lower_text: ""
  form_submission_email: ""
  submit_success_url: ""
  component_theme: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: Join us
  lower_text: Sign up to hear the latest news and progress in our fight for the sheep vote.
  form_submission_email: ""
  submit_success_url: /contact-success/
  component_theme: Light

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
