[component]
structures = ["content_blocks"]
label = "Quote"
description = "Generic quote block"
icon = "wysiwyg"
tags = ["Content"]

[props]
image = "https://source.unsplash.com/6anudmpILw4/600x400"
quote_text = "Hydra has shaped the business we have today. We have a repeatable sales process and a strategy to scale our team. I recommend Hydra to any business looking to improve their sales."
name = "Jim James"
role = "CEO of Global Corp"
component_theme = "Light"
