[component]
structures = ["content_blocks"]
label = "Call to action"
description = "Generic call to action block"
icon = "wysiwyg"
tags = ["Content"]

[props]
heading_html = "<h2><strong>Improve</strong> your sales process today</h2>"
button_label = "Get Started Free"
Button_link_url = "#"
button_variant.select = ["Transparent", "Filled"]
component_theme = "Light"
