[component]
structures = ["content_blocks"]
label = "Staff List"
description = "Lists all members within the Staff Members collection"
icon = "wysiwyg"
tags = ["Content"]

[props]
show_staff = true
heading = "Our team"
subheading = "We've built an amazing, fantastic team of developers, marketers, designers and sales people."
component_theme = "Light"
